### PR TITLE
Add `GeometryReader` implementation

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This is just an empty API at the moment. I hope it can be implemented purely in the `deferredBody` of `GeometryReader` with [the ResizeObserver API](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) without requiring any tweaks in the `Renderer` protocol or the reconciler.

Seems like I need the `domRef` modifier that writes `JSObjectRef` to a given binding working first, as discussed in #231.

### CODE REVIEW

**Comment by carson-katri** [comment]
I can work on implementing the features outlined in that issue

**Comment by MaxDesiatov** [comment]
I started some preliminary work on that, or do you have some code already?

**Comment by carson-katri** [comment]
No, I hadn’t started yet.

**Comment by MaxDesiatov** [comment]
No worries, I'll try to get some draft of that today.

**Comment by MaxDesiatov** [comment]
This is working for me now in isolated example code, but layout bugs exposed by our demo code prevent this from being added to the demo. @carson-katri @j-f1 lmk if you think it would be fine merging this as is and adding a `GeometryReader` demo in a separate PR (smaller PRs is what I prefer personally).

**Comment by j-f1** [comment]
IMO if it's a small bug or something that prevents building it shouldn't be merged in general. But if it's more complex or harder-to-solve bug, it's ok to merge then follow up with an issue or PR.

**Comment by carson-katri** [comment]
What's the layout bug preventing a demo?

**Comment by MaxDesiatov** [comment]
If you launch the demo in this branch in browsers and navigate to the `GeometryReader` item you'll see that the size doesn't change if you change the size of the viewport (I resized the browser window). It does change in the native demo though.

As far as I understand, the destination view of `NavigationView` doesn't fill all available space currently, maybe it's fixed with the `_FlexFrameLayout` changes made in #241?

**Comment by j-f1** [comment]
I got that to work after I added this CSS to `GeometryReader`:

```css
display: flex;
align-items: center;
justify-content: center;
```

…weirdly, the text *isn’t* exactly centered.

**Comment by MaxDesiatov** [comment]
These styles worked only in Safari for me and only for height, width always stays 300. I've pushed these changes for the lack of a better option, will have a look later if #241 could resolve it.

**Pull request merged**
